version: '3.7'
services:
  spring-petclinic-server:
    image: spring-petclinic-server:${ES_VERSION:-8.1.0}
    build:
      context: .
      dockerfile: ./development/server/Dockerfile
    container_name: spring-petclinic-server
    networks:
      spring-petclinic-net:
        aliases:
          - spring-petclinic-server
    ports:
      - "8080:8080"
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    environment:
      ELASTIC_APM_SERVER_URL: ${ELASTIC_APM_SERVER_URL}
      ELASTIC_APM_SECRET_TOKEN: ${ELASTIC_APM_SECRET_TOKEN}
      ELASTIC_APM_AGENT_VERSION: ${ELASTIC_APM_AGENT_VERSION}
      ELASTIC_APM_SPAN_FRAMES_MIN_DURATION: -1
      ELASTIC_APM_CAPTURE_BODY: all
      SERVER_PORT: 8080
      JAVA_PROFILE: hsqldb,jpa
      ELASTIC_APM_SERVICE_NAME: petclinic-spring
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://spring-petclinic-server:8080/"]
      interval: 10s
      retries: 10

  spring-petclinic-client:
    build:
      context: .
      dockerfile: ./development/frontend/client/Dockerfile
    image: spring-petclinic-client:${ES_VERSION:-8.1.0}
    container_name: spring-petclinic-client
    networks:
      spring-petclinic-net:
        aliases:
          - spring-petclinic-client
    ports:
      - "9000:8081"
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    environment:
      ELASTIC_APM_SERVER_URL: ${ELASTIC_APM_SERVER_URL}
      ELASTIC_APM_SECRET_TOKEN: ${ELASTIC_APM_SECRET_TOKEN}
      ELASTIC_APM_SERVER_JS_URL: ${ELASTIC_APM_SERVER_URL}
      ELASTIC_APM_SERVICE_VERSION: 1.0.0
      ELASTIC_APM_SERVICE_NAME: petclinic-client
      ELASTIC_APM_CLIENT_SERVICE_NAME: petclinic-react
      API_SERVER_URL: 'http://spring-petclinic-proxy:4000'
      SERVER_PORT: 8081
      NODE_ENV: production
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      PETCLINIC_INTERNAL_URL: "http://spring-petclinic-client:8081"
      PETCLINIC_EXTERNAL_URL: "http://localhost:9000"
      ADDRESS_SERVER: "http://spring-address-finder:5000"
    depends_on:
      - spring-petclinic-server
      - spring-address-finder
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://spring-petclinic-client:${CLIENT_SERVER_PORT:-3000}/"]
      interval: 10s
      retries: 10

  spring-petclinic-proxy:
    build:
      context: .
      dockerfile: ./development/frontend/proxy/Dockerfile
    image: spring-petclinic-proxy:${ES_VERSION:-8.1.0}
    container_name: spring-petclinic-proxy
    networks:
      spring-petclinic-net:
        aliases:
          - spring-petclinic-client
    ports:
      - "4000:4000"
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    environment:
      ELASTIC_APM_SERVER_URL: ${ELASTIC_APM_SERVER_URL}
      ELASTIC_APM_SECRET_TOKEN: ${ELASTIC_APM_SECRET_TOKEN}
      ELASTIC_APM_SERVICE_VERSION: 1.0.0
      ELASTIC_APM_SERVICE_NAME: petclinic-client
      ELASTIC_APM_CLIENT_SERVICE_NAME: petclinic-react
      API_SERVER: 'http://spring-petclinic-server:8080'
      API_PREFIX: '/api'
      ADDRESS_SERVER: 'http://spring-address-finder:5000'


  spring-address-finder:
    build:
      context: .
      dockerfile: ./development/address_finder/Dockerfile
    image: spring-address-finder:${ES_VERSION:-8.1.0}
    container_name: spring-address-finder
    networks:
      spring-petclinic-net:
        aliases:
          - spring-address-finder
    ports:
      - "5000:5000"
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    environment:
      ELASTIC_APM_SERVER_URL: ${ELASTIC_APM_SERVER_URL}
      ELASTIC_APM_SECRET_TOKEN: ${ELASTIC_APM_SECRET_TOKEN}
      ELASTIC_APM_SERVICE_VERSION: 1.0.0
      ELASTIC_APM_SERVICE_NAME: petclinic-address-finder
      ELASTIC_APM_CLIENT_SERVICE_NAME: petclinic-react
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}

networks:
  spring-petclinic-net:
    driver: bridge
volumes:
  esdata01:
    driver: local
